name: Lint and Test

on: [push]

env:
  DEV_LIB_PATH: vendor/xwp/wp-dev-lib/scripts

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run lint

  test_e2e_latest_coverage:
    needs: [lint]
    name: 'E2E tests (PHP 7.4, WordPress latest, with code coverage)'
    runs-on: ubuntu-latest

    env:
      NODE_ENV: e2e
      WP_VERSION: latest

    steps:
    - uses: actions/checkout@v2
    - uses: hmarr/debug-action@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run env:start
    - run: npm run wp -- wp core install --title=WordPress --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email --url=http://localhost:8088 --quiet
    - run: npm run wp -- wp plugin activate foo-bar
    - run: npm run build:js
    - run: npm run test:e2e:coveralls

  test_php_latest_coverage:
    needs: [lint]
    name: 'PHP tests (PHP 7.4, WordPress latest, with code coverage)'
    runs-on: ubuntu-latest

    env:
      WP_VERSION: latest
      DEV_LIB_ONLY: phpunit,coverage

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: phpunit
    - run: composer install
    - run: source "$DEV_LIB_PATH/travis.install.sh"
    - run: source "$DEV_LIB_PATH/travis.script.sh"
